name: 'Install dependencies'
description: 'Installs workflow dependencies'
runs:
  using: "composite"
  steps:
  - name: Add GOPATH to PATH
    run: echo "PATH=$PATH:$(go env GOPATH)/bin" >> $GITHUB_ENV
    shell: bash
  - name: Install protoc
    run: sudo apt install -y protobuf-compiler
    shell: bash
  - name: Install protoc plugin
    run: go get google.golang.org/protobuf/cmd/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc
    shell: bash
  - name: Install golanci-lint
    run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.32.2
    shell: bash
  - name: Install gocovmerge
    run: go get github.com/wadey/gocovmerge
    shell: bash
