# Cryptographic keys. Must be 64 hex digits.
[keys]
KEK = "0000000000000000000000000000000000000000000000000000000000000000"
ASK = "0000000000000000000000000000000000000000000000000000000000000001"
TEK = "0000000000000000000000000000000000000000000000000000000000000002"

# Auth storage configuration
[authstorage]
# Connection string for the backend database
URL = "postgresql://root@localhost:26257/auth"

# Object storage configuration
[objectstorage]
# Hostname
URL = "http://localhost:7000"

# Key ID and secret key
ID = "storageid"
Key = "storagekey"

# TLS certificate
Cert = '''-----BEGIN CERTIFICATE-----
MIIBpjCCAVigAwIBAgIUQ3byU/Dxv0eA11bPDYVC4xD36dwwBQYDK2VwMGUxCzAJBgNVBAYTAkRLMQowCAYDVQQIDAEuMQowCAYDVQQHDAEuMQwwCgYDVQQKDANmb28xGjAYBgkqhkiG9w0BCQEWC2Zvb0BiYXIuY29tMRQwEgYDVQQDDAtmb28uYmFyLmNvbTAeFw0yMDExMTgxNjM5MDVaFw0yMTExMTgxNjM5MDVaMGUxCzAJBgNVBAYTAkRLMQowCAYDVQQIDAEuMQowCAYDVQQHDAEuMQwwCgYDVQQKDANmb28xGjAYBgkqhkiG9w0BCQEWC2Zvb0BiYXIuY29tMRQwEgYDVQQDDAtmb28uYmFyLmNvbTAqMAUGAytlcAMhAEeBiCvHWsxIRPH6tSqmalACa4ckUhXGLoqFUSLef5jyoxowGDAWBgNVHREEDzANggtmb28uYmFyLmNvbTAFBgMrZXADQQAdA1YAoyBCqsFlePrYO6AP1eUgYfCKEjRUttIeSltIv+M+AEzZIU8+JB3nH684qyi8y7XwWuZVC64639WbLxoL
-----END CERTIFICATE-----'''
